services:
  jupyter:
    build: .
    image: quay.io/jupyter/scipy-notebook:2024-08-30
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "salmonisyummy"
